channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions==0.5.1
  - jupyterhub-singleuser>=3.0,<4.0
  - python=3.8
  - nbgitpuller=1.1.*
  - pip
  - git
  - numpy
  - scipy>=1.1
  - cython
  - lxml
  - astropy
  - pandas
  - scikit-image
  - h5py
  - openblas
  - pip:
    - jupyter-server-proxy==3.2.2
    - aiohttp==3.8.4
