channels:
  - conda-forge

dependencies:
  - jupyter_contrib_nbextensions
  - jupyterhub-singleuser
  - python=3.10
  - nbgitpuller
  - pip
  - git
  - numpy
  - scipy>=1.1
  - cython
  - lxml
  - astropy
  - pandas
  - scikit-image
  - h5py
  - openblas
  - pip:
    - jupyter-server-proxy @ git+https://github.com/jupyterhub/jupyter-server-proxy.git
    - aiohttp
